/**
 * Event types for AutoMaker event system
 */

export type EventType =
  | 'agent:stream'
  | 'auto-mode:event'
  | 'auto-mode:started'
  | 'auto-mode:stopped'
  | 'auto-mode:idle'
  | 'auto-mode:error'
  | 'backlog-plan:event'
  | 'feature:started'
  | 'feature:completed'
  | 'feature:stopped'
  | 'feature:error'
  | 'feature:progress'
  | 'feature:tool-use'
  | 'feature:follow-up-started'
  | 'feature:follow-up-completed'
  | 'feature:verified'
  | 'feature:committed'
  | 'project:analysis-started'
  | 'project:analysis-progress'
  | 'project:analysis-completed'
  | 'project:analysis-error'
  | 'suggestions:event'
  | 'spec-regeneration:event'
  | 'issue-validation:event'
  | 'ideation:stream'
  | 'ideation:session-started'
  | 'ideation:session-ended'
  | 'ideation:analysis'
  | 'ideation:analysis-started'
  | 'ideation:analysis-progress'
  | 'ideation:analysis-complete'
  | 'ideation:analysis-error'
  | 'ideation:suggestions'
  | 'ideation:idea-created'
  | 'ideation:idea-updated'
  | 'ideation:idea-deleted'
  | 'ideation:idea-converted'
  | 'pr_monitor_started'
  | 'pr_monitor_new_feedback'
  | 'pr_monitor_checks_changed'
  | 'pr_monitor_state_changed'
  | 'pr_monitor_stopped'
  | 'pr_monitor_error'
  | 'pr_merge_monitor_started'
  | 'pr_merge_monitor_stopped'
  | 'pr_merged'
  | 'pr_closed'
  | 'pr_merge_monitor_error'
  | 'pr_merge_pull_started'
  | 'pr_merge_pull_completed'
  | 'pr_merge_pull_failed'
  | 'feature_status_changed'
  | 'review-loop:state-changed'
  | 'review-loop:review-completed'
  | 'review-loop:refinement-started'
  | 'review-loop:refinement-completed'
  | 'review-loop:pr-feedback-received'
  | 'review-loop:ready-for-human'
  | 'review-loop:error';

export type EventCallback = (type: EventType, payload: unknown) => void;
